import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import Header from "./components/Header";
import Footer from "./components/Footer";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative min-h-screen overflow-hidden`}
      >
        {/* Global Background Image */}
        <div className="fixed inset-0 z-0">
          <Image
            src="/bg.jpg"
            alt="Background"
            fill
            className="object-cover"
            priority
          />
        </div>

        {/* Side Background Images */}
        <div className="fixed inset-0 z-10 pointer-events-none">
          {/* Left Side Image */}
          <div className="absolute left-0 top-1/2 transform -translate-y-1/2 w-24 h-32 sm:w-32 sm:h-48 md:w-48 md:h-64 lg:w-64 lg:h-80 xl:w-80 xl:h-96 opacity-40">
            <Image
              src="/bg-oneside.png"
              alt="Left Side BG"
              fill
              className="object-contain"
              priority
            />
          </div>

          {/* Right Side Image */}
          <div className="absolute right-0 top-1/2 transform -translate-y-1/2 w-24 h-32 sm:w-32 sm:h-48 md:w-48 md:h-64 lg:w-64 lg:h-80 xl:w-80 xl:h-96 scale-x-[-1] opacity-40">
            <Image
              src="/bg-oneside.png"
              alt="Right Side BG"
              fill
              className="object-contain"
              priority
            />
          </div>
        </div>

        {/* Header */}
        <Header />

        {/* Main Content */}
        <main className="relative z-20">
          {children}
        </main>

        {/* Footer */}
        <Footer />
      </body>
    </html>
  );
}
